# config.py - Astartes-Gotchi Configuration (TEST MODE - ACCELERATED EVOLUTION)
# WARNING: This is a TEST configuration with EXTREMELY fast evolution!
# DO NOT USE FOR NORMAL GAMEPLAY

# ===== GAME METADATA =====
GAME_VERSION = "0.1.0-MVP-TEST"
DEFAULT_MARINE_NAME = "Battle Brother"

# ===== TIMING CONSTANTS =====
FRAME_TIME = 0.1  # 10 FPS (100ms per frame)
UPDATE_INTERVAL = 5  # Update stats every 5 seconds (ACCELERATED)
AUTOSAVE_INTERVAL = 10  # Auto-save every 10 seconds

# ===== EVOLUTION TIMINGS (ACCELERATED FOR TESTING) =====
STAGE_DURATION_NEOPHYTE = 30  # 30 seconds (was 1 hour)
STAGE_DURATION_SCOUT = 60  # 60 seconds (was 2 days)
STAGE_DURATION_BATTLE_BROTHER = 90  # 90 seconds (was 4 days)
# Total: 3 minutes to reach Veteran

# ===== STAT DECAY RATES (ACCELERATED) =====
DECAY_SUSTENANCE = 2  # -2 per update (gentler for testing)
DECAY_BATTLE_FURY = 1  # -1 per update
DECAY_GENESEED_PURITY = 0  # Disabled for testing

# ===== CORRUPTION SYSTEM =====
CORRUPTION_PASSIVE_GAIN = 1  # +1 per 30s (faster)
CORRUPTION_THRESHOLD_CHAOS = 60
CORRUPTION_THRESHOLD_GENESEED_DECAY = 50

# ===== EVOLUTION THRESHOLDS (unchanged) =====
# Loyalist chapters
ULTRAMARINE_DISCIPLINE_MIN = 75
ULTRAMARINE_CORRUPTION_MAX = 20
ULTRAMARINE_CARE_MISTAKES_MAX = 2

GREY_KNIGHT_DISCIPLINE_MIN = 90
GREY_KNIGHT_CORRUPTION_MAX = 0
GREY_KNIGHT_CARE_MISTAKES_MAX = 0
GREY_KNIGHT_WHISPERS_RESISTED_MIN = 10

IMPERIAL_FIST_DISCIPLINE_MIN = 60
IMPERIAL_FIST_COMBAT_EXP_MAX = 50
IMPERIAL_FIST_CORRUPTION_MAX = 30

BLOOD_ANGEL_COMBAT_EXP_MIN = 70
BLOOD_ANGEL_DISCIPLINE_MIN = 40
BLOOD_ANGEL_DISCIPLINE_MAX = 70
BLOOD_ANGEL_CORRUPTION_MAX = 40

SPACE_WOLF_DISCIPLINE_MAX = 50
SPACE_WOLF_SUSTENANCE_MIN = 60
SPACE_WOLF_CORRUPTION_MAX = 35

SALAMANDER_GENESEED_MIN = 70
SALAMANDER_DISCIPLINE_MIN = 50
SALAMANDER_DISCIPLINE_MAX = 80
SALAMANDER_CARE_MISTAKES_MAX = 3

# Chaos paths
KHORNE_COMBAT_EXP_MIN = 80
KHORNE_DISCIPLINE_MAX = 30
KHORNE_CORRUPTION_MIN = 60

SLAANESH_STIMM_COUNT_MIN = 50
SLAANESH_CORRUPTION_MIN = 50

NURGLE_POOP_COUNT_MIN = 20
NURGLE_CORRUPTION_MIN = 55

TZEENTCH_WARP_MEDICINE_REQUIRED = True
TZEENTCH_WHISPERS_ACCEPTED_MIN = 5
TZEENTCH_CORRUPTION_MIN = 65

# ===== FEED SYSTEM =====
FEED_RATION_SUSTENANCE = 20
FEED_CORPSE_STARCH_SUSTENANCE = 20
FEED_CORPSE_STARCH_DISCIPLINE_PENALTY = 5
FEED_CORPSE_STARCH_PENALTY_CHANCE = 0.1

FEED_STIMM_BATTLE_FURY = 15
FEED_STIMM_CORRUPTION = 2

# ===== PRAYER SYSTEM =====
PRAYER_CORRUPTION_REDUCTION = 15
PRAYER_GENESEED_BOOST = 5
PRAYER_DISCIPLINE_BOOST = 5
PRAYER_COOLDOWN = 30  # 30 seconds (was 3 hours)
PRAYER_CORRUPTION_LOCKOUT = 80

# ===== CHAOS WHISPER SYSTEM (ACCELERATED FOR TESTING) =====
# Emperor's Whisper
EMPEROR_WHISPER_CHANCE = 0.15  # 15% chance to get Emperor whisper instead of Chaos

# Cooldowns (ACCELERATED)
WHISPER_COOLDOWN_GLOBAL = 60  # 1 minute between ANY whispers
WHISPER_COOLDOWN_PER_GOD = 120  # 2 minutes before same god can appear again

# Stage-based frequencies (minimum time between whispers)
WHISPER_FREQUENCY_NEOPHYTE = 120  # 2 minutes (rare for beginners)
WHISPER_FREQUENCY_SCOUT = 90  # 1.5 minutes
WHISPER_FREQUENCY_BATTLE_BROTHER = 60  # 1 minute
WHISPER_FREQUENCY_VETERAN = 60  # 1 minute (constant temptation)

# Khorne Challenge (Rapid Tapping)
KHORNE_TAP_TARGET = 20  # 20 taps required (test mode - raw frame counting, achievable)
KHORNE_DURATION = 5.0  # 5 seconds to complete

# Slaanesh Challenge (Slow Drag)
SLAANESH_MIN_TIME = 4.0  # Minimum drag duration (seconds)
SLAANESH_MAX_TIME = 6.0  # Maximum drag duration (seconds)
SLAANESH_MIN_DISTANCE = 250  # Minimum pixels to drag
SLAANESH_MAX_SPEED = 40  # Maximum pixels/second (enforced!)

# Nurgle Challenge (Stillness)
NURGLE_DURATION = 5.0  # 5 seconds of stillness
NURGLE_MOVEMENT_THRESHOLD = 0.1  # G-force threshold (CALIBRATED: quiet=0.00-0.01, movement=0.02-0.05)

# Tzeentch Challenge (Shake/Rotate)
TZEENTCH_DURATION = 4.0  # 4 seconds to complete
TZEENTCH_SHAKE_THRESHOLD = 0.5  # G-force threshold (LOWERED: shake peaks=0.31-2.42, using lower threshold)
TZEENTCH_REQUIRED_SHAKES = 5  # Required shake count (test mode - easy for testing)

# ===== MINIGAME SCORING (unchanged) =====
HERESY_CHECK_VICTORY_MIN = 8
HERESY_CHECK_DRAW_MIN = 5
BOLTER_DRILL_VICTORY_KILLS = 15
BOLTER_DRILL_DRAW_KILLS = 10
DODGE_WARP_PERFECT_HITS = 0
DODGE_WARP_VICTORY_HITS = 3
DODGE_WARP_DEFEAT_HITS = 6
DODGE_WARP_SEVERE_HITS = 7

# ===== UI COLORS (RGB888 24-bit format for UIFlow2) =====
COLOR_IMPERIAL_GOLD = 0xFFD700
COLOR_AQUILA_WHITE = 0xFFFFFF
COLOR_PURITY_SEAL = 0xFF0000

# Stats
COLOR_GENESEED = 0x0000FF
COLOR_BATTLE_FURY = 0xFF0000
COLOR_SUSTENANCE = 0x00FF00
COLOR_DISCIPLINE = 0xFFD700
COLOR_CORRUPTION = 0x8B00FF

# Chaos
COLOR_KHORNE = 0xCC0000
COLOR_SLAANESH = 0xFF1493
COLOR_NURGLE = 0x7FFF00
COLOR_TZEENTCH = 0x00BFFF

# UI
COLOR_BG = 0x000000
COLOR_TEXT = 0xFFFFFF
COLOR_BUTTON = 0x404040
COLOR_BUTTON_ACTIVE = 0x808080

# ===== DISPLAY LAYOUT =====
SCREEN_WIDTH = 320
SCREEN_HEIGHT = 240
HEADER_HEIGHT = 30
SPRITE_AREA_HEIGHT = 120
STATS_AREA_HEIGHT = 50
BUTTONS_AREA_HEIGHT = 40
SPRITE_SIZE = 64

# ===== SOUND =====
BEEP_FREQUENCY_FEED = 800
BEEP_FREQUENCY_COMBAT = 1200
BEEP_FREQUENCY_PRAYER = 600
BEEP_FREQUENCY_CORRUPTION = 200
BEEP_FREQUENCY_EVOLUTION = 1000
BEEP_DURATION = 100

# ===== STASIS POD =====
STASIS_DAILY_USES = 1

# ===== DEATH PENALTIES =====
DEATH_CHAOS_CORRUPTION_PENALTY = 10

# ===== DEBUG MODE =====
DEBUG = True  # Keep debug on for testing

